#!/usr/bin/env bash

set -e

if [ "$(uname -s)" != 'Darwin' ] ; then
  echo 'Unsupported OS' >&2
  exit 1
fi

which brew &>/dev/null || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install ag ctags gawk git fswatch nvm python python3 tmux z zsh
brew reinstall --HEAD macvim neovim vim

HOMESHICK="$HOME/.homesick/repos/homeshick"
[ -d "$HOMESHICK" ] || git clone git://github.com/andsens/homeshick.git "$HOMESHICK"
which homeshick &>/dev/null || source "$HOMESHICK/homeshick.sh"
[ -d "$(dirname "$HOMESHICK")/dotfiles" ] || (
  if [ -n "$ME" ] ; then
    homeshick clone git@github.com/aymericbeaumet/dotfiles.git
  else
    homeshick clone git://github.com/aymericbeaumet/dotfiles.git
  fi
  homeshick link dotfiles
)

exit 0
