" clear all autocommands
autocmd!
" break away from old vi compatibility
set nocompatible
" found vim config file and config dir
let s:vim_conf = expand('<sfile>:p')
let s:vim_dir = fnamemodify(s:vim_conf, ':h') . '/.vim'

" {{{ Vundle

filetype off " required by Vundle

let &runtimepath .= ',' . s:vim_dir . '/bundle/vundle'
if (exists("g:vundle_install_dir"))
  call vundle#rc(g:vundle_install_dir)
else
  call vundle#rc()
endif

" Load Vundle first
Bundle 'gmarik/vundle'

" Languages plugins
Bundle '2072/PHP-Indenting-for-VIm'
Bundle 'indenthtml.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-git'
Bundle 'tpope/vim-markdown'

" Themes plugins
Bundle 'croaker/mustang-vim'
Bundle 'wombat256.vim'

" Tools plugins
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Bundle 'Lokaltog/vim-easymotion'
Bundle 'LustyJuggler'
Bundle 'Shougo/neocomplcache.vim'
Bundle 'SirVer/ultisnips'
Bundle 'a.vim'
Bundle 'airblade/vim-rooter'
Bundle 'bingaman/vim-sparkup'
Bundle 'chrisbra/NrrwRgn'
Bundle 'closetag.vim'
Bundle 'ervandew/supertab'
Bundle 'godlygeek/tabular'
Bundle 'jimsei/winresizer'
Bundle 'jistr/vim-nerdtree-tabs'
Bundle 'kien/ctrlp.vim'
Bundle 'majutsushi/tagbar'
Bundle 'myusuf3/numbers.vim'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-sleuth'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'

" }}}

" {{{ File type / Syntax detection / Theme

syntax enable
filetype plugin indent on
set t_Co=256
set background=dark
silent! colorscheme wombat256mod
hi CursorLine cterm=bold
set synmaxcol=800       " don't try to highlight lines longer than 800 characters
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$' " hight VCS conflict markers

" }}}

" {{{ Global options

set shell=zsh           " shell for :sh
set autoread            " watch for file changes by other programs
set autowrite           " automatically save before :next and :make
set laststatus=2        " status line always on
set encoding=utf-8      " ensure proper encoding
set ttyfast             " we have a fast terminal
set nowritebackup       " no backup file while editing
set modelines=0         " don't care about modeline
set viminfo=            " don't use or save viminfo files
set fileformats=unix,mac,dos    " support all three newline formats

set backup                       " enable backup files
set backupdir=~/.vim/tmp/backup/

set undofile                     " enable undo files
set undolevels=1000              " number of undo level
set undoreload=10000             " number of lines to save for undo
set undodir=~/.vim/tmp/undo/

set swapfile                     " enable swap files
set directory=~/.vim/tmp/swap/

" Make those folders automatically if they don't already exist.
if !isdirectory(expand(&undodir))
    call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
    call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
    call mkdir(expand(&directory), "p")
endif

" }}}

" {{{ User Interface

set timeoutlen=350      " time to wait when a part of a maped sequence is typped
set matchtime=3         " tenths of second to show the matching bracket
set nonumber            " don't show line number
set cmdheight=1         " explicitly set the command line height
set showcmd             " show (partial) command in the last line of the screen
set scrolloff=8         " keep at least 5 lines after the cusor when scrolling
set sidescrolloff=10    " (same as above for side scrolling)
set lazyredraw          " only redraw when needed
set nolist              " hide invisible characters
set wrap                " split the line if it is too long
set shortmess=atI       " disable vim welcome message and shorter messages
set wildmenu            " better command line completion menu
set cursorline          " highlight cursor line
set wildmode=list:longest,list,full " `-> better
set wildignore+=*.o,*.so,*.a,*.dylib,*.pyc  " ignore compiled files
set wildignore+=*.zip,*.gz,*.xz             " ignore compressed files
set wildignore+=.*.sw*,*~                   " ignore temporary files

" }}}

" {{{ Text editing && Search behavior
"
set backspace=2         " fix backspace (on some OS/term)
set cpoptions=ces$      " make the 'cw' and like commands put a $ at the end
set ignorecase          " ignore case when searching
set smartcase           "  `-> except if there is one uppercase character
set incsearch           " show matches as soon as posseble
set hlsearch            " highlight last search matches
set wrapscan            " searches wrap around the end of the file
set diffopt=filler,iwhite " ignore all whitespace and sync
set showmatch           " show the matching bracket when inserting
set completeopt=menu,longest,preview " more autocomplete <Ctrl>-P options
set nostartofline       " leave my cursor position alone!
set foldmethod=manual   " ensure that foldmethod is manual
set virtualedit=block   " allow the cursor to go in to 'invalid' places
set wrap linebreak textwidth=0 " disable autowrap
set history=1000        " increase history size

" disable auto comment
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" }}}

" {{{ Indentation / Tabulations

set autoindent          " auto-indentation (most of time override by plugins)
set copyindent          " copy the previous indentation on autoindenting
set expandtab           " insert `shiftwidth` spaces when using <Tab>
set shiftwidth=2        " n spaces when using <Tab>
set softtabstop=2       " n spaces when using <Tab>
set tabstop=2           " n spaces when using <Tab>
set hidden              " when I close a tab, don't remove the buffer

" }}}

" {{{ Errors

" turn off error bells 
set noerrorbells
set novisualbell
set t_vb=

" }}}

" {{{ Binds

" easy switch between tabs
nnoremap <silent> <S-h> gT
nnoremap <silent> <S-l> gt

" up and down are more logical with g
nnoremap <silent> j gj
nnoremap <silent> k gk

" center on each search result
nnoremap <silent> n nzz
nnoremap <silent> <S-n> Nzz

" define leading key
let g:mapleader = ','
let mapleader = ','

" quickly edit/reload the vimrc file
nnoremap <silent> <leader>ve :e $MYVIMRC<CR>
nnoremap <silent> <leader>vs :source $MYVIMRC<CR>

" hide last search matches
nnoremap <silent> <leader><space> :nohlsearch<CR>

" use `,d`  `,D` `,x` `,X` to delete without altering the yanked stack
noremap <silent> <leader>d "_d
noremap <silent> <leader>D "_D
noremap <silent> <leader>x "_x
noremap <silent> <leader>X "_X

" copy from the cursor to the end of line using Y
nnoremap <silent> Y y$

" map <Space> to / (search)
nnoremap <silent> <space> /

" leave insert mode using `jj`
inoremap <silent> jj <esc>

" fuck you, help key.
noremap <F1> <nop>
inoremap <F1> <nop>

" man key on M
nnoremap <silent> M K

" keep the cursor in place while joining lines
nnoremap J mzJ`z

" split line
nnoremap S i<cr><esc>^mwgk:silent! s/\v +$//<cr>:noh<cr>`w

" use ^a and ^e to move in command line
cnoremap <c-a> <home>
cnoremap <c-e> <end>

" }}}

" {{{ Abbrev

" create/move/close tab
cabbrev tn tabnew
cabbrev tm tabmove
cabbrev tq tabclose

" close buffer
cabbrev bq bdelete

" }}}

" {{{ Plugins extra-configuration

" CtrlP
let g:ctrlp_map = '<leader>o'
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc)$|(^|[/\\])\.(hg|git|bzr|svn)($|[/\\])|__init__\.py'
let g:ctrlp_working_path_mode = 0
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_max_files = 1000
let g:ctrlp_max_depth = 10
nnoremap <silent> <leader>bo :CtrlPBuffer<CR>

" easymotion
let g:EasyMotion_leader_key = '<leader>w'

" html
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

" lusty juggler
nmap <silent> <leader>bg <leader>lj

" narrowregion
let g:nrrw_rgn_nohl = 1
noremap <leader>r :NarrowRegion<CR>

" neocomplcache
let g:neocomplcache_enable_at_startup = 1
let g:neocomplcache_enable_smart_case = 1
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" nerdtree
let NERDTreeShowHidden = 1 " show hidden files
let NERDTreeWinSize = 40
let NERDTreeMinimalUI = 1
nnoremap <silent> <leader>e :NERDTreeTabsToggle<CR>

" php indent
let g:PHP_vintage_case_default_indent = 1

" powerline
set noshowmode " hide the duplicate mode in bottom status bar

" syntastic
let g:syntastic_mode_map = { 'mode': 'passive' }
let g:syntastic_check_on_wq = 0
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_c_compiler_options = "-Wall -Wextra"
nnoremap <silent> <leader>s :SyntasticCheck<CR>
nnoremap <silent> <leader>S :SyntasticToggleMode<CR>

" tabular
nnoremap <silent> <leader>a :Tabularize /
vnoremap <silent> <leader>a :Tabularize /

" tagbar
let g:tagbar_autoclose = 1
let g:tagbar_autofocus = 1
let g:tagbar_show_visibility = 1 " show private/protected/public
let g:tagbar_compact = 1
let g:tagbar_left = 1
nnoremap <silent> <leader>t :TagbarToggle<CR>

" }}}
