start-at-login = true

after-login-command = []

after-startup-command = [
  'exec-and-forget sketchybar',
]

exec-on-workspace-change = ['/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
accordion-padding = 0

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = ['secondary', 'main']

[gaps]
inner.horizontal = [{ monitor."^built-in retina display$" = 16 }, 16]
inner.vertical =   [{ monitor."^built-in retina display$" = 16 }, 16]
outer.top =        [{ monitor."^built-in retina display$" = 16 }, 48]
outer.right =      [{ monitor."^built-in retina display$" = 16 }, 16]
outer.bottom =     [{ monitor."^built-in retina display$" = 16 }, 16]
outer.left =       [{ monitor."^built-in retina display$" = 16 }, 16]

[mode.main.binding]

# disable useless shortcuts
cmd-h = [] # "hide application"
cmd-alt-h = [] # "hide others"

# reload config
alt-r = ['mode service', 'reload-config', 'mode main']

# workspace manipulation
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']

# layout manipulation
alt-a = ['flatten-workspace-tree', 'layout accordion']
alt-t = ['flatten-workspace-tree', 'layout tiles']

# focus tiles/apps
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
cmd-ctrl-a        = 'exec-and-forget osascript -e "tell application \"Alacritty.app\" to activate"'
cmd-ctrl-c        = 'exec-and-forget osascript -e "tell application \"ChatGPT.app\" to activate"'
cmd-ctrl-f        = 'exec-and-forget osascript -e "tell application \"Firefox.app\" to activate"'
cmd-ctrl-g        = 'exec-and-forget osascript -e "tell application \"Figma.app\" to activate"'
cmd-ctrl-i        = 'exec-and-forget osascript -e "tell application \"Messages.app\" to activate"'
cmd-ctrl-l        = 'exec-and-forget osascript -e "tell application \"Linear.app\" to activate"'
cmd-ctrl-n        = 'exec-and-forget osascript -e "tell application \"Notion.app\" to activate"'
cmd-ctrl-o        = 'exec-and-forget osascript -e "tell application \"Obsidian.app\" to activate"'
cmd-ctrl-p        = 'exec-and-forget osascript -e "tell application \"Postico 2.app\" to activate"'
cmd-ctrl-s        = 'exec-and-forget osascript -e "tell application \"Slack.app\" to activate"'
cmd-ctrl-slash    = 'exec-and-forget osascript -e "tell application \"Postman.app\" to activate"'
cmd-ctrl-w        = 'exec-and-forget osascript -e "tell application \"WhatsApp.app\" to activate"'
cmd-ctrl-y        = 'exec-and-forget osascript -e "tell application \"Spotify.app\" to activate"'
cmd-ctrl-backtick = 'exec-and-forget open "obsidian://open?vault=%F0%9F%A7%A0%20Brain&file=Scratchpad"'

# move tile
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# resize tile
alt-minus = 'resize smart -100'
alt-equal = 'resize smart +100'
alt-0 = 'balance-sizes'

# move to workspace 1 by default
[[on-window-detected]]
run = ['move-node-to-workspace 1']
