export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:$PATH"
export PATH="/usr/texbin:$PATH" # Add tex binaries
export PATH="$HOME/bin:$PATH" # Custom local bin
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
