[general]
live_config_reload = true
ipc_socket = true

[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"
style  = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style  = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style  = "Bold Italic"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = """

"""
key = "NumpadEnter"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"

[scrolling]
history = 0

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "default"]

[window]
decorations = "buttonless"
padding = { x = 0, y = 0 }
dynamic_padding = false
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"
opacity = 0.99
blur = true
